### ISSUE TITLE
[Feature] Integrate ISO-639-1 language codes

### ISSUE THREAD

**Issue by jakewilliami** [cjdoris/Countries.jl#2]
For example [pycountry](https://github.com/flyingcircusio/pycountry) has [this functionality](https://stackoverflow.com/a/32773402/12069968).

Furthermore, I think getting some inspiration from pycountry's interface would be helpful in use of this package (especially if people are coming from Python).

I am happy to help implement this.  Let me know what you think.

Edit: there is also the [`iso639`](https://github.com/noumar/iso639) Python module which adds support for this, so an option would be to say "no" to this feature and I can make a separate package :-)

**Comment by cjdoris** [comment]
Based on this comment I have rewritten the whole package!

It's now very simple and just provides the country information in a list. It's up to the user what to do with that list (e.g. it's easy to turn it into a DataFrame or make a dict to convert between the different codes). All the other functionality seemed like unnecessary fluff, in hindsight.

At the same time I added other lists like languages and currencies. It's really just a nicer presentation of the information in `iso_codes_jll.jl`.

It's not released but is on the main branch. Please try it out and let me know what you think.

**Comment by jakewilliami** [comment]
Great work Christopher!  This is really great.  A very simple interface with each type you expose from the ISO standards.  One functionality I would like is to look up values in the `Countries.all_*` lists.  As such, I have implemented this in #4.  Let me know what you think.

P.S., the only thing this package is missing is docstrings :)

**Comment by cjdoris** [comment]
I released this a while ago - with do strings!
